# Custom Language File for Launcher Customizer

[ejs.app]
title = "물징어 게임"

[ejs.landing]
mediaGitHubURL = "https://github.com/mchlauncher/MoolSquid"
mediaXURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = ""
mediaSoopURL = "#"
mediaChzzkURL = "#"
screenshotsTooltip = "스크린샷"

[ejs.settings]
sourceGithubLink = "https://github.com/mchlauncher/MoolSquid"
supportLink = "https://github.com/mchlauncher/MoolSquid/issues"

[ejs.welcome]
welcomeHeader = "물징어 게임"
welcomeDescription = ""
welcomeDescCTA = "[계속] 버튼을 눌러 계속 진행하여 주세요."